COC = {
    'WC': {
        '1Herbrumer': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'bakerbarkley': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'McMillan', 'TE': 'Kraft'}, 
        'BassBert': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'beastm0de': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'blackpanda4255': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'block_west18': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'Bummi': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'chaefer77': {'QB': 'Daniels', 'RB': 'Williams', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'copyk': {'QB': 'Nix', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'DanTheMan84': {'QB': 'Daniels', 'RB': 'Williams', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'Deckhard': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'Effe A.': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'elpres': {'QB': 'Daniels', 'RB': 'Williams', 'WR': 'Jefferson', 'TE': 'Kraft'}, 
        'fa94': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'fredie_io': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'Hans Hansen': {'QB': 'Jackson', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kincaid'},
        'haube37': {'QB': 'Nix', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'herbstibears': {'QB': 'Nix', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kraft'}, 
        'Hiase': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'Immortellus': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'JackPOT': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'jans12': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'KingCookie': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'kunfc.': {'QB': 'Jackson', 'RB': 'Williams', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'Lambo23': {'QB': 'Herbert', 'RB': 'Williams', 'WR': 'Jefferson', 'TE': 'Kraft'}, 
        'LeTomster': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'luckenbuesser': {'QB': 'Daniels', 'RB': 'Mixon', 'WR': 'Jefferson', 'TE': 'Kraft'}, 
        'Lunatic': {'QB': 'Nix', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'Marcello': {'QB': 'Daniels', 'RB': 'Williams', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'marvhin23': {'QB': 'Daniels', 'RB': 'Williams', 'WR': 'Jefferson', 'TE': 'Kraft'}, 
        'Matze Luki': {'QB': 'Jackson', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'MCO': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Freiermuth'}, 
        'Merlyn112': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'Mirarot': {'QB': 'Jackson', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'mogli_dk': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'McMillan', 'TE': 'Kraft'}, 
        'Neyinoo': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'Pascal': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'pate1703': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'PatKau1904': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'philadeagles': {'QB': 'Nix', 'RB': 'Barkley', 'WR': 'McMillan', 'TE': 'Freiermuth'}, 
        'Ptough(Pete)': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'},
        'SchlagiUSR': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'Stoni': {'QB': 'Jackson', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'Tsubasa': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'wiglgrimpft': {'QB': 'Nix', 'RB': 'Irving', 'WR': 'Sutton', 'TE': 'Andrews'}, 
        'xhailmurray': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'McMillan', 'TE': 'Kraft'}, 
        'ys_db_21': {'QB': 'Daniels', 'RB': 'Williams', 'WR': 'Nacua', 'TE': 'Kincaid'}
    },
    'DR': {
        '1Herbrumer': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'bakerbarkley': {'QB': 'Allen', 'RB': 'Cook', 'WR': 'Collins', 'TE': 'Ertz'}, 
        'BassBert': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'beastm0de': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'blackpanda4255': {'QB': '', 'RB': '', 'WR': '', 'TE': ''},
        'block_west18': {'QB': 'Allen', 'RB': 'Cook', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'Bummi': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Ertz'}, 
        'chaefer77': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Smith', 'TE': ''}, 
        'copyk': {'QB': 'Mahomes', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'DanTheMan84': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'Deckhard': {'QB': 'Allen', 'RB': 'Cook', 'WR': 'Collins', 'TE': 'Ertz'}, 
        'Effe A.': {'QB': 'Mahomes', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'elpres': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'LaPorta'}, 
        'fa94': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'fredie_io': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Hans Hansen': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'haube37': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'herbstibears': {'QB': 'Stafford', 'RB': 'Gibbs', 'WR': 'Collins', 'TE': 'Kelce'}, 
        'Hiase': {'QB': 'Mahomes', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Goedert'},
        'Immortellus': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Ertz'}, 
        'JackPOT': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'jans12': {'QB': 'Mahomes', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'KingCookie': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'kunfc.': {'QB': 'Mahomes', 'RB': 'Gibbs', 'WR': 'Collins', 'TE': 'Ertz'},
        'Lambo23': {'QB': 'Mahomes', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Kelce'},
        'LeTomster': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'},
        'luckenbuesser': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'},
        'Lunatic': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Marcello': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'},
        'marvhin23': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Smith', 'TE': 'Ertz'},
        'Matze Luki': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Collins', 'TE': 'Ertz'},
        'MCO': {'QB': 'Mahomes', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Goedert'},
        'Merlyn112': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'Collins', 'TE': 'Goedert'}, 
        'Mirarot': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Ertz'}, 
        'mogli_dk': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'Neyinoo': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Smith', 'TE': 'Ertz'}, 
        'Pascal': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'pate1703': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'PatKau1904': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Collins', 'TE': 'Ertz'}, 
        'philadeagles': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'LaPorta'},
        'Ptough(Pete)': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'SchlagiUSR': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'Stoni': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'Tsubasa': {'QB': 'Mahomes', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'wiglgrimpft': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Smith', 'TE': 'Ertz'}, 
        'xhailmurray': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'ys_db_21': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'Collins', 'TE': 'Ertz'}
    }, 
    'CF': {
        '1Herbrumer': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'bakerbarkley': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Bills', 'TE': 'Kincaid'}, 
        'BassBert': {'QB': 'Daniels', 'RB': 'Commanders', 'WR': 'Eagles', 'TE': 'Kincaid'}, 
        'beastm0de': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'blackpanda4255': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'block_west18': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Kincaid'}, 
        'Bummi': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Kincaid'}, 
        'chaefer77': {'QB': 'Daniels', 'RB': 'Chiefs', 'WR': 'Commanders', 'TE': 'Ertz'}, 
        'copyk': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'DanTheMan84': {'QB': 'Allen', 'RB': 'Commanders', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'Deckhard': {'QB': 'Allen', 'RB': 'Chiefs', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'Effe A.': {'QB': 'Allen', 'RB': 'Chiefs', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'elpres': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'fa94': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'fredie_io': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Hans Hansen': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'haube37': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'herbstibears': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Hiase': {'QB': 'Daniels', 'RB': 'Chiefs', 'WR': 'Eagles', 'TE': 'Kincaid'}, 
        'Immortellus': {'QB': 'Daniels', 'RB': 'Commanders', 'WR': 'Bills', 'TE': 'Kelce'}, 
        'JackPOT': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'jans12': {'QB': 'Mahomes', 'RB': 'Chiefs', 'WR': 'Chiefs', 'TE': 'Kelce'}, 
        'KingCookie': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Kincaid'}, 
        'kunfc.': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'Lambo23': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'LeTomster': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'luckenbuesser': {'QB': 'Hurts', 'RB': 'Bills', 'WR': 'Bills', 'TE': 'Kelce'}, 
        'Lunatic': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Marcello': {'QB': 'Mahomes', 'RB': 'Commanders', 'WR': 'Commanders', 'TE': 'Kelce'}, 
        'marvhin23': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Matze Luki': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Bills', 'TE': 'Goedert'}, 
        'MCO': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Merlyn112': {'QB': 'Daniels', 'RB': 'Commanders', 'WR': 'Eagles', 'TE': 'Kincaid'}, 
        'Mirarot': {'QB': 'Allen', 'RB': 'Commanders', 'WR': 'Commanders', 'TE': 'Kincaid'},
        'mogli_dk': {'QB': 'Hurts', 'RB': 'Commanders', 'WR': 'Eagles', 'TE': 'Kincaid'},
        'Neyinoo': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Ertz'}, 
        'Pascal': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'pate1703': {'QB': 'Daniels', 'RB': 'Bills', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'PatKau1904': {'QB': 'Daniels', 'RB': 'Bills', 'WR': 'Commanders', 'TE': 'Kincaid'},
        'philadeagles': {'QB': 'Daniels', 'RB': 'Chiefs', 'WR': 'Eagles', 'TE': 'Goedert'}, 
        'Ptough(Pete)': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'SchlagiUSR': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'Stoni': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Kincaid'}, 
        'Tsubasa': {'QB': 'Hurts', 'RB': 'Bills', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'wiglgrimpft': {'QB': 'Allen', 'RB': 'Bills', 'WR': 'Bills', 'TE': 'Kincaid'}, 
        'xhailmurray': {'QB': 'Daniels', 'RB': 'Commanders', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'ys_db_21': {'QB': 'Hurts', 'RB': 'Bills', 'WR': 'Commanders', 'TE': 'Goedert'}
    }, 
    'SB': {
        '1Herbrumer': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'bakerbarkley': {'Player1': 'Hurts', 'Player2': 'Goedert', 'Player3': 'Schuster'}, 
        'BassBert': {'Player1': '', 'Player2': '', 'Player3': ''},
        'beastm0de': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'blackpanda4255': {'Player1': '', 'Player2': '', 'Player3': ''},
        'block_west18': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'Bummi': {'Player1': 'Brown', 'Player2': 'Pacheco', 'Player3': 'Butker'}, 
        'chaefer77': {'Player1': 'Worthy', 'Player2': 'Smith', 'Player3': 'Hunt'},
        'copyk': {'Player1': 'Worthy', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'DanTheMan84': {'Player1': 'Worthy', 'Player2': 'Hunt', 'Player3': 'Goedert'}, 
        'Deckhard': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'Effe A.': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'elpres': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'fa94': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'fredie_io': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'Hans Hansen': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'haube37': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'herbstibears': {'Player1': 'Worthy', 'Player2': 'Smith', 'Player3': 'Butker'}, 
        'Hiase': {'Player1': 'Hunt', 'Player2': 'Schuster', 'Player3': 'Butker'}, 
        'Immortellus': {'Player1': 'Worthy', 'Player2': 'Brown', 'Player3': 'Hunt'}, 
        'JackPOT': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'jans12': {'Player1': 'Smith', 'Player2': 'Pacheco', 'Player3': 'Schuster'}, 
        'KingCookie': {'Player1': 'Worthy', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'kunfc.': {'Player1': 'Worthy', 'Player2': 'Brown', 'Player3': 'Goedert'}, 
        'Lambo23': {'Player1': 'Barkley', 'Player2': 'Goedert', 'Player3': 'Butker'}, 
        'LeTomster': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'luckenbuesser': {'Player1': 'Smith', 'Player2': 'Pacheco', 'Player3': 'Butker'}, 
        'Lunatic': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'Marcello': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'marvhin23': {'Player1': 'Barkley', 'Player2': 'Brown', 'Player3': 'Hunt'}, 
        'Matze Luki': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'MCO': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'Merlyn112': {'Player1': 'Worthy', 'Player2': 'Hurts', 'Player3': 'Goedert'}, 
        'Mirarot': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'mogli_dk': {'Player1': 'Smith', 'Player2': 'Mahomes', 'Player3': 'Schuster'}, 
        'Neyinoo': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'Pascal': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'pate1703': {'Player1': 'Hurts', 'Player2': 'Goedert', 'Player3': 'Schuster'}, 
        'PatKau1904': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'philadeagles': {'Player1': 'Brown', 'Player2': 'Goedert', 'Player3': 'Butker'}, 
        'Ptough(Pete)': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'SchlagiUSR': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'Stoni': {'Player1': 'Worthy', 'Player2': 'Hurts', 'Player3': 'Butker'}, 
        'Tsubasa': {'Player1': 'Worthy', 'Player2': 'Brown', 'Player3': 'Butker'}, 
        'wiglgrimpft': {'Player1': 'Pacheco', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'xhailmurray': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'ys_db_21': {'Player1': 'Smith', 'Player2': 'Kelce', 'Player3': 'Butker'}
    }
}

scoring_settings = {
    'pass_int': -2.0,
    # 'pass_2pt': 0,# geändert von 2
    'pass_yd': 0.04,
    'pass_td': 4.0,
    'rec_td': 6.0,
    'rec_yd': 0.1,
    # 'rec_2pt': 0,# geändert von 2
    'rec': 1.0,
    'rush_td': 6.0,
    # 'rush_2pt': 0,# geändert von 2
    'rush_yd': 0.1,
    'fum_lost': -2.0,
    'fum_rec': 2.0,
    # 'fum': 0
}

wc_round_player = {
    'Jackson': {'player_id': '4881', 'price': 5, 'position': 'QB', 'points': 0},
    'Daniels': {'player_id': '11566', 'price': 3, 'position': 'QB', 'points': 0},
    'Nix': {'player_id': '11563', 'price': 1, 'position': 'QB', 'points': 0},
    'Herbert': {'player_id': '6797', 'price': 0, 'position': 'QB', 'points': 0},
    'Barkley': {'player_id': '4866', 'price': 5, 'position': 'RB', 'points': 0},
    'Williams': {'player_id': '8150', 'price': 3, 'position': 'RB', 'points': 0},
    'Irving': {'player_id': '11584', 'price': 1, 'position': 'RB', 'points': 0},
    'Mixon': {'player_id': '4018', 'price': 0, 'position': 'RB', 'points': 0},
    'Jefferson': {'player_id': '6794', 'price': 5, 'position': 'WR', 'points': 0},
    'Nacua': {'player_id': '9493', 'price': 3, 'position': 'WR', 'points': 0},
    'Sutton': {'player_id': '5045', 'price': 1, 'position': 'WR', 'points': 0},
    'McMillan': {'player_id': '11618', 'price': 0, 'position': 'WR', 'points': 0},
    'Andrews': {'player_id': '5012', 'price': 5, 'position': 'TE', 'points': 0},
    'Freiermuth': {'player_id': '7600', 'price': 3, 'position': 'TE', 'points': 0},
    'Kraft': {'player_id': '9484', 'price': 1, 'position': 'TE', 'points': 0},
    'Kincaid': {'player_id': '10236', 'price': 0, 'position': 'TE', 'points': 0}
}

div_round_player = {
    'Allen': {'player_id': '4984', 'price': 5, 'position': 'QB', 'points': 0},
    'Mahomes': {'player_id': '4046', 'price': 3, 'position': 'QB', 'points': 0},
    'Goff': {'player_id': '3163', 'price': 1, 'position': 'QB', 'points': 0},
    'Stafford': {'player_id': '421', 'price': 0, 'position': 'QB', 'points': 0},
    'Henry': {'player_id': '3198', 'price': 5, 'position': 'RB', 'points': 0},
    'Gibbs': {'player_id': '9221', 'price': 3, 'position': 'RB', 'points': 0},
    'Cook': {'player_id': '8138', 'price': 1, 'position': 'RB', 'points': 0},
    'Robinson': {'player_id': '8154', 'price': 0, 'position': 'RB', 'points': 0},
    'McLaurin': {'player_id': '5927', 'price': 5, 'position': 'WR', 'points': 0},
    'Collins': {'player_id': '7569', 'price': 3, 'position': 'WR', 'points': 0},
    'Smith': {'player_id': '7525', 'price': 1, 'position': 'WR', 'points': 0},
    'Williams': {'player_id': '8148', 'price': 0, 'position': 'WR', 'points': 0},
    'LaPorta': {'player_id': '10859', 'price': 5, 'position': 'TE', 'points': 0},
    'Kelce': {'player_id': '1466', 'price': 3, 'position': 'TE', 'points': 0},
    'Goedert': {'player_id': '5022', 'price': 1, 'position': 'TE', 'points': 0},
    'Ertz': {'player_id': '1339', 'price': 0, 'position': 'TE', 'points': 0}
}

# conf_round_player = {
#     'Allen': {'Allen':{'player_id': '4984', 'price': 5, 'position': 'QB', 'points': 0}},
#     'Daniels': {'Daniels':{'player_id': '11566', 'price': 3, 'position': 'QB', 'points': 0}},
#     'Hurts': {'Hurts':{'player_id': '6904', 'price': 1, 'position': 'QB', 'points': 0}},
#     'Mahomes': {'Mahomes':{'player_id': '4046', 'price': 0, 'position': 'QB', 'points': 0}},
#     'PHI RBs':{
#         'Barkley': {'player_id': '4866', 'price': 5, 'position': 'RB', 'points': 0},
#         'Gainwell': {'player_id': '7567', 'price': 5, 'position': 'RB', 'points': 0}
#         },
#     'BUF RBs':{
#         'Cook': {'player_id': '8138', 'price': 3, 'position': 'RB', 'points': 0},
#         'Davis': {'player_id': '11575', 'price': 3, 'position': 'RB', 'points': 0}
#         },
#     'WAS RBs':{
#         'Robinson': {'player_id': '8154', 'price': 1, 'position': 'RB', 'points': 0},
#         'Ekeler': {'player_id': '4663', 'price': 1, 'position': 'RB', 'points': 0}
#         },
#     'KC RBs':{
#         'Pacheco': {'player_id': '8205', 'price': 0, 'position': 'RB', 'points': 0},
#         'Hunt': {'player_id': '4098', 'price': 0, 'position': 'RB', 'points': 0}
#         },
#     'PHI WRs':{
#         'AJ Brown': {'player_id': '5859', 'price': 5, 'position': 'WR', 'points': 0},
#         'Smith': {'player_id': '7525', 'price': 5, 'position': 'WR', 'points': 0}
#         },
#     'WAS WRs':{
#         'McLaurin': {'player_id': '5927', 'price': 3, 'position': 'WR', 'points': 0},
#         'Brown': {'player_id': '7587', 'price': 3, 'position': 'WR', 'points': 0}
#     },
#     'KC WRs':{
#         'Worthy': {'player_id': '11624', 'price': 1, 'position': 'WR', 'points': 0},
#         'Brown': {'player_id': '5848', 'price': 1, 'position': 'WR', 'points': 0}
#     },
#     'BUF WRs':{
#         'Cooper': {'player_id': '2309', 'price': 0, 'position': 'WR', 'points': 0},
#         'Shakir': {'player_id': '8134', 'price': 0, 'position': 'WR', 'points': 0}
#     },
#     'Kelce': {'Kelce':{'player_id': '1466', 'price': 5, 'position': 'TE', 'points': 0}},
#     'Ertz': {'Ertz':{'player_id': '1339', 'price': 3, 'position': 'TE', 'points': 0}},
#     'Goedert': {'Goedert':{'player_id': '5022', 'price': 1, 'position': 'TE', 'points': 0}},
#     'Kincaid': {'Kincaid':{'player_id': '10236', 'price': 0, 'position': 'TE', 'points': 0}}
# }


conf_round_player = {
    'Allen': {'player_id': '4984', 'price': 5, 'position': 'QB', 'points': 0, 'group': 'QB'},
    'Daniels': {'player_id': '11566', 'price': 3, 'position': 'QB', 'points': 0, 'group': 'QB'},
    'Hurts': {'player_id': '6904', 'price': 1, 'position': 'QB', 'points': 0, 'group': 'QB'},
    'Mahomes': {'player_id': '4046', 'price': 0, 'position': 'QB', 'points': 0, 'group': 'QB'},
    'Barkley': {'player_id': '4866', 'price': 5, 'position': 'RB', 'points': 0, 'group': 'PHI RBs'},
    'Gainwell': {'player_id': '7567', 'price': 5, 'position': 'RB', 'points': 0, 'group': 'PHI RBs'},
    'Cook': {'player_id': '8138', 'price': 3, 'position': 'RB', 'points': 0, 'group': 'BUF RBs'},
    'Davis': {'player_id': '11575', 'price': 3, 'position': 'RB', 'points': 0, 'group': 'BUF RBs'},
    'Robinson': {'player_id': '8154', 'price': 1, 'position': 'RB', 'points': 0, 'group': 'WAS RBs'},
    'Ekeler': {'player_id': '4663', 'price': 1, 'position': 'RB', 'points': 0, 'group': 'WAS RBs'},
    'Pacheco': {'player_id': '8205', 'price': 0, 'position': 'RB', 'points': 0, 'group': 'KC RBs'},
    'Hunt': {'player_id': '4098', 'price': 0, 'position': 'RB', 'points': 0, 'group': 'KC RBs'},
    'AJ Brown': {'player_id': '5859', 'price': 5, 'position': 'WR', 'points': 0, 'group': 'PHI WRs'},
    'Smith': {'player_id': '7525', 'price': 5, 'position': 'WR', 'points': 0, 'group': 'PHI WRs'},
    'McLaurin': {'player_id': '5927', 'price': 3, 'position': 'WR', 'points': 0, 'group': 'WAS WRs'},
    'D. Brown': {'player_id': '7587', 'price': 3, 'position': 'WR', 'points': 0, 'group': 'WAS WRs'},
    'Worthy': {'player_id': '11624', 'price': 1, 'position': 'WR', 'points': 0, 'group': 'KC WRs'},
    'M. Brown': {'player_id': '5848', 'price': 1, 'position': 'WR', 'points': 0, 'group': 'KC WRs'},
    'Cooper': {'player_id': '2309', 'price': 0, 'position': 'WR', 'points': 0, 'group': 'BUF WRs'},
    'Shakir': {'player_id': '8134', 'price': 0, 'position': 'WR', 'points': 0, 'group': 'BUF WRs'},
    'Kelce': {'player_id': '1466', 'price': 5, 'position': 'TE', 'points': 0, 'group': 'TEs'},
    'Ertz': {'player_id': '1339', 'price': 3, 'position': 'TE', 'points': 0, 'group': 'TEs'},
    'Goedert': {'player_id': '5022', 'price': 1, 'position': 'TE', 'points': 0, 'group': 'TEs'},
    'Kincaid': {'player_id': '10236', 'price': 0, 'position': 'TE', 'points': 0, 'group': 'TEs'}
}

super_bowl_challenge = [
    ["Hurts", 1, 6904],
    ["Mahomes", 1, 4046],
    ["Kelce", 1, 1466],
    ["Barkley", 1, 4866],
    ["Worthy", 3, 11624],
    ["Smith", 3, 7525],
    ["AJ Brown", 3, 5859],
    ["Goedert", 3, 5022],
    ["Pacheco", 5, 8205],
    ["Hunt", 5, 4098],
    ["Butker", 5, 4227],
    ["Schuster", 5, 4040]
]